export const lineupData = [
  "Brittany Dawn Samples",
  "Em Jamison",
  "Madylin Goins",
  "Rachel Crowe",
  "Ande Fee",
  "Kadie Meadows",
  "Emma Le",
  "Melody Youngblood",
  "Honey Wright",
  "Erin Sliney",
  "Tiffany Williams",
  "Mary Wright",
  "Lemon Grass",
  "Sarah Fightmaster",
  "Jen Marie",
  "Anna Kline",
  "Liz Frazier",
  "Sydney Adams",
];
